services:
  server:
    volumes:
      - ../server/app:/app/app
      - ../server/uploads:/app/uploads
      - ../server/models:/app/models:ro

    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload

  db:
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    ports:
      - "${REDIS_PORT}:6379"